:toc:
:toc-placement!:

// gEmoji for admonitions, see
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Links (alphabetical order)
:apache_license: http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]
:application_monitoring_operator: https://github.com/integr8ly/application-monitoring-operator[application-monitoring-operator]
:export_policy: https://aerogear.org/legal/export.html[AeroGear Export Policy]
:aerogear_freenode: irc://irc.freenode.net/aerogear[#aerogear on FreeNode IRC]
:aerogear_jira: https://issues.jboss.org/projects/AEROGEAR/issues[AeroGear on JBoss Jira]
:aerogear_matrix: https://matrix.to/#/!IipcvbGVqkiTUQauSC:matrix.org[#aerogear:matrix.org on Matrix]
:mailing_list: https://groups.google.com/forum/#!forum/aerogear[Google Groups Mailing List]
:minishift: https://github.com/minishift/minishift[Minishift]
:rh_product_security: https://access.redhat.com/security/team/contact[Red Hat Product Security team]

= App Metrics Operator

ifdef::status[]
.*Project health*
image:https://travis-ci.com/aerogear/app-metrics-operator.svg?branch=master[Build Status (Travis), link=https://travis-ci.com/aerogear/app-metrics-operator.svg?branch=master]
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
endif::[]


The App Metrics Operator for Kubernetes provides an easy way to
install and manage AeroGear App Metrics Service on Kubernetes.

toc::[]


== Limitations

// https://issues.jboss.org/browse/AEROGEAR-9162
[NOTE]
====
This operator currently only works on OpenShift. This is because it
provisions `Route`s and `ImageStream`s. In future we aim to make it
work on vanilla Kubernetes also.
====


== Installation

As a user with admin permissions, you can install the
app-metrics-operator and a sample CR in your OpenShift cluster as follows:

....
make cluster/prepare
make install
....


== Configuration

=== Image Streams

The operator uses 2 image streams and what image streams to use are configurable
with environment variables.

App Metrics image stream is created within the same namespace by the operator.
However, for Postgres the image stream in `openshift` namespace is used.

The following table shows the available
environment variable names, along with their default values:


.Environment Variables
|===
|Name |Default |Purpose

|`APP_METRICS_IMAGE_STREAM_NAME`
|`app-metrics-imagestream`
| Name of the App Metrics image stream that will be created by the operator.

|`APP_METRICS_IMAGE_STREAM_TAG`
|`latest`
| Tag of the App Metrics image stream that will be created by the operator.

|`APP_METRICS_IMAGE_STREAM_INITIAL_IMAGE`
|`docker.io/aerogear/aerogear-app-metrics:0.0.13`
| Initial image for the App Metrics image stream that will be created by the operator.

|`POSTGRES_IMAGE_STREAM_NAMESPACE`
|`openshift`
| Namespace to look for the Postgres image stream.

|`POSTGRES_IMAGE_STREAM_NAME`
|`postgresql`
| Name of the Postgres image stream to look for.

|`POSTGRES_IMAGE_STREAM_TAG`
|`10`
| Tag of the Postgres image stream.

|===

CAUTION: Re-deploying this operator with customized images will cause
_all_ instances owned by the operator to be updated.


=== Container Names

If you would like to modify the container names, you can use the following environment variables.

.Environment Variables
|===
|Name |Default

|`APP_METRICS_CONTAINER_NAME`
|`appmetrics`

|`POSTGRES_CONTAINER_NAME`
|`postgresql`

|===


=== Backups

The `BACKUP_IMAGE` environment variable configures what image to use for backing up
the custom resources created by this operator. Default value is `quay.io/integreatly/backup-container:1.0.8`.


== Custom Resources (aka How to get value from this operator)

=== AppMetricsService

This is the main installation resource kind. Creation of a valid
AppMetricsService CR will result in a functional App Metrics Service
deployed to your namespace.

`AppMetricsService` has no fields that are configurable.

An example AppMetricsService resource is available at
`./deploy/crds/metrics_v1alpha1_appmetricsservice_cr.yaml`:

.metrics_v1alpha1_appmetricsservice_cr.yaml
[source,yaml]
----
apiVersion: metrics.aerogear.org/v1alpha1
kind: AppMetricsService
metadata:
  name: example-appmetricsservice
----

To create this, you can run:

....
kubectl apply -n app-metrics -f ./deploy/crds/metrics_v1alpha1_appmetricsservice_cr.yaml
....

To see the created instance then, you can run:

....
kubectl get appmetricsservice example-appmetricsservice -n app-metrics -o yaml
....

=== AppMetricsConfig

This is the service consumption resource kind. Creation of a valid
AppMetricsConfig CR will write the client config to
a config map in the CR namespace.

`AppMetricsConfig` has no fields that are configurable.

An example AppMetricsConfig resource is available at
`./deploy/crds/metrics_v1alpha1_appmetricsconfig_cr.yaml`:

.metrics_v1alpha1_appmetricsconfig_cr.yaml
[source,yaml]
----
apiVersion: metrics.aerogear.org/v1alpha1
kind: AppMetricsConfig
metadata:
  name: example-app
----

To create this, you can run:

....
kubectl apply -n app-metrics -f ./deploy/crds/metrics_v1alpha1_appmetricsconfig_cr.yaml
....

To see the created instance then, you can run:

....
kubectl get appmetricsconfig example-app -n app-metrics -o yaml
....

The config map created will have the name pattern `<cr-app-name>-metrics`. For the example above,
you can run the following command to get the config map.

....
kubectl get configmap example-app-metrics -n app-metrics -o yaml
....

It will have content similar to this:

....
apiVersion: v1
data:
  SDKConfig: >-
    {"url":
    "https://example-appmetricsservice-appmetrics-app-metrics.openshift.cluster.hostname"}
kind: ConfigMap
...
....


== Getting help

All AeroGear projects use the same communication channels.

*Issue tracker*

Our main issue tracker is {aerogear_jira}. Issues may also be created
here on GitHub for individual projects.

*Chat*

For synchronous real-time chat, we use Matrix/IRC. These are bridged
together, so you can choose which is more convenient for you:
{aerogear_matrix} or {aerogear_freenode}.

*Discussion list*

For important conversations, we discuss asynchronously on this
{mailing_list}. This is great for discussions that should involve many
people in different time zones, and allows us to easily link back to
conversations in future.

== Development

=== Prerequisites

- Access to an OpenShift cluster with admin privileges to be able to
  create Roles.  {minishift} is suggested.

- Go, Make, dep, operator-sdk, kubectl (kubectl can just be a symlink
  to oc)

=== Running the operator

1. Prepare the operator project:

....
make cluster/prepare
....

2. Run the operator (locally, not in OpenShift):

....
make code/run
....

3. Create an App Metrics Service instance (in another terminal):

....
make install
....

4. Watch the status of your App Metrics Service instance provisioning (optional):

....
watch -n1 "kubectl get po -n app-metrics && echo '' && kubectl get appmetricsservice -o yaml -n app-metrics"
....

5. If you want to be able to work with resources that require the
local instance of your operator to be able to talk to the App Metrics instance
in the cluster, then you'll need to make a corresponding domain name
available locally. Something like the following should work, by adding
an entry to /etc/hosts for the example Service that's created, then
forwarding the port from the relevant Pod in the cluster to the local
machine. Run this in a separate terminal, and ctrl+c to clean it up
when finished:

6. Create an App Metrics Config instance:

...
make example-app/apply
...

7. Watch the status of your App Metrics Config (optional):

....
watch -n1 "kubectl get po -n app-metrics && echo '' && kubectl get appmetricsconfig -o yaml -n app-metrics"
....

8. Check the config map created:

...
kubectl get configmap -n app-metrics example-app-metrics -o yaml
...


9. When finished, clean up:
....
make cluster/clean
....

== Security Response

If you've found a security issue that you'd like to disclose
confidentially please contact the {rh_product_security}.

== Legal

The App Metrics Operator is licensed under the {apache_license}
License, and is subject to the {export_policy}.
