apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-metrics-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-metrics-operator
  template:
    metadata:
      labels:
        name: app-metrics-operator
    spec:
      serviceAccountName: app-metrics-operator
      containers:
        - name: app-metrics-operator
          image: quay.io/aerogear/app-metrics-operator:master
          command:
          - app-metrics-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: APP_NAMESPACES
              # Replace this with a comma (e.g. namespace,othernamespace) separated list of namespaces which the operator will action app crs
              value: "app-metrics-apps"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "app-metrics-operator"
