kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-metrics-operator
subjects:
- kind: ServiceAccount
  name: app-metrics-operator
  namespace: app-metrics
roleRef:
  kind: ClusterRole
  name: app-metrics-operator
  apiGroup: rbac.authorization.k8s.io
