# Monitor Service (Metrics)
apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-metrics-operator
  name: app-metrics-operator
spec:
  ports:
    - name: metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
  selector:
    name: app-metrics-operator
  sessionAffinity: None
  type: ClusterIP